# Generated by Django 3.2.5 on 2022-11-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_letter', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('words', models.TextField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('end_letter', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unique_word',
                'managed': True,
            },
        ),
    ]
